name: "Malicious workflow"
on: [push, pull_request]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
      with:
        username: whatever
        password: whatever
        repository: whatever
        tags: whatever